[package]
name = "rust_os"
version = "0.1.0"
authors = ["Kyle Galloway <kyle.galloway.1993@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"
spin = "0.4.5"
multiboot2 = "0.3.2"